/**
 * Parser for custom MTG set HTML files generated by the user's set creator tool.
 *
 * Expected HTML structure:
 * <li class="card">
 *   <div class="card-inner">
 *     <img class="card-image" src="card0.jpg" />
 *     <span class="name">Card Name</span>
 *     <span class="casting-cost">...</span>  (text like "2WU" or <img alt="W"> elements)
 *     <span class="type">Creature — Human Wizard</span>
 *     <span class="rarity"><img alt="C|U|R|M" /></span>
 *     <span class="text">Card text here</span>
 *     <span class="pt">2/3</span>
 *     <span class="number">001</span>
 *   </div>
 * </li>
 */

export interface ParsedCustomCard {
  index: number
  name: string
  manaCost: string | null
  cmc: number
  typeLine: string
  colors: string[]
  colorIdentity: string[]
  rarity: 'common' | 'uncommon' | 'rare' | 'mythic'
  oracleText: string | null
  power: string | null
  toughness: string | null
  collectorNumber: string
  imageFileName: string
  isBooster: boolean
}

const RARITY_MAP: Record<string, 'common' | 'uncommon' | 'rare' | 'mythic'> = {
  'C': 'common',
  'U': 'uncommon',
  'R': 'rare',
  'M': 'mythic',
}

const MANA_SYMBOL_COLORS: Record<string, string> = {
  'W': 'W',
  'U': 'U',
  'B': 'B',
  'R': 'R',
  'G': 'G',
}

/**
 * Decode HTML entities (numeric and named) to their actual characters.
 */
function decodeHtmlEntities(text: string): string {
  // Decode numeric entities: &#8217; &#233; &#x2019; etc.
  let decoded = text.replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code, 10)))
  decoded = decoded.replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)))
  // Decode common named entities
  const namedEntities: Record<string, string> = {
    '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&apos;': "'",
    '&nbsp;': ' ', '&eacute;': 'é', '&egrave;': 'è', '&ecirc;': 'ê', '&euml;': 'ë',
    '&agrave;': 'à', '&acirc;': 'â', '&auml;': 'ä', '&icirc;': 'î', '&iuml;': 'ï',
    '&ocirc;': 'ô', '&ouml;': 'ö', '&ucirc;': 'û', '&uuml;': 'ü', '&ugrave;': 'ù',
    '&ccedil;': 'ç', '&oelig;': 'œ', '&aelig;': 'æ', '&ntilde;': 'ñ',
    '&lsquo;': '\u2018', '&rsquo;': '\u2019', '&ldquo;': '\u201C', '&rdquo;': '\u201D',
    '&ndash;': '\u2013', '&mdash;': '\u2014', '&hellip;': '\u2026',
  }
  for (const [entity, char] of Object.entries(namedEntities)) {
    decoded = decoded.replaceAll(entity, char)
  }
  return decoded
}

function extractSpanContent(cardHtml: string, className: string): string {
  // Match span with class, handling both self-closing and content spans
  const regex = new RegExp(`<span[^>]*class=["']${className}["'][^>]*>(.*?)</span>`, 's')
  const match = cardHtml.match(regex)
  return match ? match[1].trim() : ''
}

function parseManaCost(costHtml: string): { manaCost: string; colors: string[]; cmc: number } {
  if (!costHtml || costHtml.trim() === '') {
    return { manaCost: '', colors: [], cmc: 0 }
  }

  // Extract mana symbols from <img alt="X"> tags
  const imgSymbols: string[] = []
  const imgRegex = /<img[^>]*alt=["']([^"']+)["'][^>]*>/g
  let match
  while ((match = imgRegex.exec(costHtml)) !== null) {
    imgSymbols.push(match[1])
  }

  // If there are img tags, use those; otherwise parse text content
  let symbols: string[]
  if (imgSymbols.length > 0) {
    symbols = imgSymbols
  } else {
    // Parse text like "2WU" or "{2}{W}{U}"
    const text = costHtml.replace(/<[^>]*>/g, '').trim()
    if (!text) return { manaCost: '', colors: [], cmc: 0 }

    // Handle {X} notation
    const braceRegex = /\{([^}]+)\}/g
    const braceSymbols: string[] = []
    let braceMatch
    while ((braceMatch = braceRegex.exec(text)) !== null) {
      braceSymbols.push(braceMatch[1])
    }

    if (braceSymbols.length > 0) {
      symbols = braceSymbols
    } else {
      // Parse compact notation like "2WU"
      symbols = []
      let i = 0
      while (i < text.length) {
        if (/\d/.test(text[i])) {
          // Collect multi-digit numbers
          let num = ''
          while (i < text.length && /\d/.test(text[i])) {
            num += text[i]
            i++
          }
          symbols.push(num)
        } else if (/[WUBRGXC]/.test(text[i].toUpperCase())) {
          symbols.push(text[i].toUpperCase())
          i++
        } else {
          i++
        }
      }
    }
  }

  // Build mana cost string in {X} notation
  const manaCost = symbols.map(s => `{${s}}`).join('')

  // Derive colors
  const colorSet = new Set<string>()
  let cmc = 0

  for (const symbol of symbols) {
    if (MANA_SYMBOL_COLORS[symbol]) {
      colorSet.add(symbol)
      cmc += 1
    } else if (symbol === 'X') {
      // X counts as 0 for CMC
    } else {
      const num = parseInt(symbol, 10)
      if (!isNaN(num)) {
        cmc += num
      }
    }
  }

  return {
    manaCost,
    colors: Array.from(colorSet).sort(),
    cmc,
  }
}

function parseRarity(rarityHtml: string): 'common' | 'uncommon' | 'rare' | 'mythic' {
  // Look for <img alt="C|U|R|M">
  const imgMatch = rarityHtml.match(/<img[^>]*alt=["']([CURM])["'][^>]*>/)
  if (imgMatch) {
    return RARITY_MAP[imgMatch[1]] || 'common'
  }

  // Fallback: check text content
  const text = rarityHtml.replace(/<[^>]*>/g, '').trim().toUpperCase()
  if (text in RARITY_MAP) {
    return RARITY_MAP[text]
  }

  return 'common'
}

function parsePowerToughness(ptHtml: string): { power: string | null; toughness: string | null } {
  const text = ptHtml.replace(/<[^>]*>/g, '').trim()
  if (!text || text === '') return { power: null, toughness: null }

  const parts = text.split('/')
  if (parts.length !== 2) return { power: null, toughness: null }

  return {
    power: parts[0].trim(),
    toughness: parts[1].trim(),
  }
}

function isToken(typeLine: string): boolean {
  const lower = typeLine.toLowerCase()
  return lower.includes('jeton') || lower.includes('token')
}

function extractImageFileName(cardHtml: string): string {
  // MSE format: image filename is in <a href='cardXXX.jpg'> inside the name span
  const hrefMatch = cardHtml.match(/<span[^>]*class=["']name["'][^>]*>[\s\S]*?<a[^>]*href=["']([^"']+\.(?:jpg|jpeg|png))["']/i)
  if (hrefMatch) return hrefMatch[1]

  // Fallback: <img class="card-image">
  const imgMatch = cardHtml.match(/<img[^>]*class=["']card-image["'][^>]*src=["']([^"']+)["'][^>]*>/)
  if (imgMatch) return imgMatch[1]

  // Fallback: first img src that looks like a card image
  const firstImg = cardHtml.match(/<img[^>]*src=["']([^"']+\.(?:jpg|jpeg|png))["'][^>]*>/i)
  return firstImg ? firstImg[1] : ''
}

export function parseCustomSetHtml(html: string): ParsedCustomCard[] {
  const cards: ParsedCustomCard[] = []

  // Split on card items - handle both <li class="card"> and <div class="card">
  const cardRegex = new RegExp('<li[^>]*class=["\'][^"\']*card[^"\']*["\'][^>]*>(.*?)<\\/li>', 'gs')
  let cardMatch
  let index = 0

  while ((cardMatch = cardRegex.exec(html)) !== null) {
    const cardHtml = cardMatch[1]

    const name = decodeHtmlEntities(
      extractSpanContent(cardHtml, 'name')
        .replace(/<[^>]*>/g, '') // strip any inner HTML
        .trim()
    )

    if (!name) continue

    const costHtml = extractSpanContent(cardHtml, 'casting-cost')
    const { manaCost, colors, cmc } = parseManaCost(costHtml)

    const typeLine = decodeHtmlEntities(
      extractSpanContent(cardHtml, 'type')
        .replace(/<[^>]*>/g, '')
        .trim()
    )

    const rarityHtml = extractSpanContent(cardHtml, 'rarity')
    const rarity = parseRarity(rarityHtml)

    // Support both 'text' and 'rule-text' class names (MSE uses 'rule-text')
    const rawOracleText = extractSpanContent(cardHtml, 'rule-text') || extractSpanContent(cardHtml, 'text')
    const oracleText = decodeHtmlEntities(
      rawOracleText
        .replace(/<br\s*\/?>/gi, '\n') // preserve line breaks
        .replace(/<[^>]*>/g, '') // strip HTML
        .replace(/&nbsp;/g, ' ')
        .trim()
    ) || null

    const ptHtml = extractSpanContent(cardHtml, 'pt')
    const { power, toughness } = parsePowerToughness(ptHtml)

    // Support both 'number' and 'card-number' class names (MSE uses 'card-number')
    const numberText = (extractSpanContent(cardHtml, 'card-number') || extractSpanContent(cardHtml, 'number'))
      .replace(/<[^>]*>/g, '')
      .trim()
    // Handle MSE format "X/Y" (e.g. "1/385") — extract just the number part
    const numberPart = numberText.includes('/') ? numberText.split('/')[0].trim() : numberText
    const collectorNumber = numberPart
      ? String(parseInt(numberPart, 10) || index + 1).padStart(3, '0')
      : String(index + 1).padStart(3, '0')

    const imageFileName = extractImageFileName(cardHtml)

    cards.push({
      index,
      name,
      manaCost: manaCost || null,
      cmc,
      typeLine,
      colors,
      colorIdentity: colors, // Same as colors for custom sets
      rarity,
      oracleText,
      power,
      toughness,
      collectorNumber,
      imageFileName,
      isBooster: !isToken(typeLine),
    })

    index++
  }

  return cards
}
